### ISSUE TITLE
Installation issue : ./commix.py: No such file or directory

### ISSUE THREAD

**Issue by W0x404** [stasinopoulos/commix#10]
I got an issue after installing :      
`(*) Starting the installer... [ SUCCEED ]<br>`
`(*) Installing commix into the /usr/share/commix... [ SUCCEED ]</br>`
`(*) Installing commix to /usr/bin/commix... [ SUCCEED ]</br>`
`(!) The installation is finished! Type 'commix' to launch it.</br>`
`@:/opt$ commix `
`/usr/bin/commix: line 2: ./commix.py: No such file or directory`

Fixed by changing /usr/share/commix/commix-master/commix.py in /user/bin/commix

commix-master is missing in the default pass.

**Comment by stasinopoulos** [comment]
Hey @W0x404, sorry but i can't reproduce the error you received. 
What distro of Linux did you used for the installation?

**Comment by W0x404** [comment]
I am on a Google Compute MV, a debian 7.8 distro.
If you got a google compute account, I can create a VM and share to you this access.

**Comment by stasinopoulos** [comment]
That's very weird. I 've already checked it on multiple VMs (i.e Debian, Ubuntu, Kali) and the installer works fine. Could you please try to install it on an other VM (i.e Kali)?
