### ISSUE TITLE
Please add git tags on releases

### ISSUE THREAD

**Issue by offensive-security** [stasinopoulos/commix#16]
Firstly, thanks for sharing your code with the open-source world. 

As you may or may not be aware, we have included your tool in our [Kali Linux](https://www.kali.org/) penetration testing distribution so it can be easily installed by our large user-base. 

As the distribution includes hundreds of tools, keeping them updated is a significant undertaking. We would like to ensure that your tool is always kept as current as possible so that our users can benefit from the latest features and fixes. You could help us in this task immensely by [tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your releases here on GitHub. Tagging releases allows us to automate the process of checking for new releases, ensuring that tools get updated far more quickly.

Tagging can be included in your workflow very easily and would go a long way to helping us keep your tool updated in our distribution. The most common type of tag is the "lightweight" version as follows (where 0.3 is the new version number):

`git-tag v0.3`

Thanks!

**Comment by stasinopoulos** [comment]
Firstly, I would like to thank you for including commix in Kali.
Tagging is done (https://github.com/stasinopoulos/commix/releases).
Please let me know if everything is ok.
Thanks!

**Comment by offensive-security** [comment]
Yep, everything looks great! You can see your tagged releases here: 
https://github.com/stasinopoulos/commix/tags

Our scripts check for updates on a daily basis and inform us once a new release is detected.

Thanks again!
