### ISSUE TITLE
UnboundLocalError: local variable 'identified_os' referenced before assignment

### ISSUE THREAD

**Issue by NullArray** [stasinopoulos/commix#22]
After the latest update i am having problems employing the shellshock technique for command injection. I haven't tested any other techniques as of yet since i was working on this particular host.

```
commix.py --proxy=62.197.227.163:80 --shellshock --verbose --url=http://vulnhost.com/cgi-bin/wspd_cgi.sh/streamfile.p?Serial=03061&Seq=5
```
Returns the following error.

```
Traceback (most recent call last):
  File "C:\PentestBox\bin\WebApplications\commix\commix.py", line 403, in <module>
    main()
  File "C:\PentestBox\bin\WebApplications\commix\commix.py", line 247, in main
    print Style.BRIGHT + "(!) The server's operating system was identified as " + Style.UNDERLINE + identified_os  + Style.RESET_ALL + "." + Style.RESET_ALL
UnboundLocalError: local variable 'identified_os' referenced before assignment
Seq: invalid floating point argument: =1
```

I tried it on another host i had identified as vulnerable to shellshock and the same thing happened. I'd appreciate any help, thanks in advance.

**Comment by stasinopoulos** [comment]
Hey @NullArray thanks for the issue. Please confirm that is ok now.

**Comment by NullArray** [comment]
It works now thank you, however it may be interesting to note that commix notified me with the following.

```
(^) Warning: Heuristics have failed to identify server's operating system.
(?) Do you recognise the server's operating system? [(W)indows/(U)nix/(q)uit] >
```
I don't know why exactly, obviously i selected unix because i had identified the host as vulnerable to shellshock. However if i set the injection technique to shellshock i'd reckon it would be reasonable for the program to assume the target OS is unix based, maybe some logic can be implemented to omit this type of behavior under these circumstances?
