### ISSUE TITLE
Previous session and added options

### ISSUE THREAD

**Issue by thenight7** [stasinopoulos/commix#26]
Hey.
During the test, I received a positive response:

(!) The (GET) 'order id' parameter is vulnerable to Blind Command Injection. (+) Type: Blind Command Injection (+) Technique: Time-Based Injection Technique (+) Payload:; str = $ (echo CQHGXC); str1 = $ {# str}; if [6 -ne $ {str1}] ; then sleep 0; else sleep 1; fi
(?) Do you want a Pseudo-Terminal? [Y / n / q]> y

Added: --current-user --hostname --is-root --is-admin --sys-info --users --passwords --privileges

As it happened: commix --tor --url="http://www.blablabla.com/order.php?orderid=INJECT_HERE" --current-user --hostname --technique="time-based" --is-root --is-admin --sys-info --users --passwords --privileges

And most of the vulnerability can not find (a very long time to find). As already found a substitute option? (+) Payload:; str = $ (echo CQHGXC); str1 = $ {# str}; if [6 -ne $ {str1}]; then sleep 0; else sleep 1; fi
The results of the previous session are not saved? (example:SQLMAP)
When adding an option, the test begins again, that is not very convenient.
Sry, my bad eng.

**Comment by stasinopoulos** [comment]
@thenight7 thank you for your suggestion.

**Comment by stasinopoulos** [comment]
Added support for resuming to the latest injection point(s) and storing / retrieving executed commands via a session (sqlite3) file.
