### ISSUE TITLE
Commix failing when creating file

### ISSUE THREAD

**Issue by Slavery** [stasinopoulos/commix#30]
Hi, i've been having this issue alot whereby i'd get a series of errors, ending with 'Index out of range", notably when creating a file. I've tried updating python and commix but no luck, unless i'm updating them wrong...? Would appreciate help, thanks

**Comment by stasinopoulos** [comment]
Hello @Slavery and thanks for the issue. Could you please provide me with the screenshot of the command(s) that you have entered as well as the error output?

**Comment by Slavery** [comment]
sure, here are the pictures
![commixproblem](https://cloud.githubusercontent.com/assets/19230043/15093237/323748ba-1479-11e6-9f7c-8c4a97cba20d.JPG)
![commixproblem2](https://cloud.githubusercontent.com/assets/19230043/15093238/39448ce4-1479-11e6-9aec-8d41320573a0.JPG)

thanks in adv

**Comment by Slavery** [comment]
i see this has been labeled as a bug, is there a known fix as of yet? thanks
