### ISSUE TITLE
Suggestions or issues ?

### ISSUE THREAD

**Issue by HugoDelval** [stasinopoulos/commix#31]
Hi there it's a great tool you built there !
I would have 2 suggestions/issues:
- parsing JSON parameters like in SQLmap -> it detects if the body is JSON via the Header application/json then extract all the parameters in the JSON data
- is the proxy option working fine ? I tried to used it with burp suite to authenticate against an original webapp and even though it said "" Testing proxy 127.0.0.1:8080... [  SUCCEED  ] "" I didn't see any trafic in my HTTP history in burp suite.
![burp_fail](https://cloud.githubusercontent.com/assets/9109308/15827617/211d234c-2c0c-11e6-82ae-e920735cbe55.png)

**Comment by stasinopoulos** [comment]
Hey @HugoDelval, 
firstly i would like to thank you for your suggestion about the  JSON parameters parsing. Concerning your issue, the proxy option seems to be working fine for me. Please check again your proxy options and try again.
![screenshot from 2016-06-06 18-42-48](https://cloud.githubusercontent.com/assets/5289251/15829661/4f08c570-2c1d-11e6-85df-5aaeb61ff505.png)

**Comment by HugoDelval** [comment]
Hi, indeed the JSON functionality works fine ! Sorry about it. I solved my proxy issue here : #32
