### ISSUE TITLE
/root/commix/src/core/modules/shellshock/shellshock.py exception raised

### ISSUE THREAD

**Issue by eranvak** [stasinopoulos/commix#34]
Hi, 

I have been came across exception in the Shellshock module python file, 
the exception is happening in line number 736 **"print "\n" + settings.print_critical_msg(err_msg)",** when the err_msg variable does not referenced before :(

in order to mitigate it I just added a line before with assignment  err_msg = ''
take it into your consideration in next release :)

**Comment by stasinopoulos** [comment]
Hello @eranvak and thanks for the issue. Could you please provide me with the screenshot of the error?
