### ISSUE TITLE
Err in Shellshock.py

### ISSUE THREAD

**Issue by eranvak** [stasinopoulos/commix#37]
Hey, 

When I tried to execute the script to check for Shellshock vulnerability I came across the above mentioned issue. 
Add the fix to your next push :)

![capture](https://cloud.githubusercontent.com/assets/7777720/17030318/a2958a48-4f77-11e6-933c-fef6b31d0a85.PNG)

**Comment by stasinopoulos** [comment]
Hey, thanks for the heads up! This fix is on que!

**Comment by eranvak** [comment]
NP...
Love Commix :) It's AWSOME!
