### ISSUE TITLE
Write logfile in proper path

### ISSUE THREAD

**Issue by epsilon77** [stasinopoulos/commix#39]
Hi!

I am working to include commix in Debian, However, commix write logfile in the path where is launched,  for this reason, I created this patch to make that commix write logfile in proper path (Home directory). 

[02_write_log_in_home.diff](
https://anonscm.debian.org/cgit/pkg-security/commix.git/tree/debian/patches/02_write_log_in_home.diff?h=master)

Thanks :)

**Comment by stasinopoulos** [comment]
Hello!
Firstly, i would like to thank you for working to include commix in Debian.
Regarding the patch that you sent me, commix by default writes logfiles in the path where it is launched, so i am not going to alter this feature.
