### ISSUE TITLE
PHP Reverse TCP not working 

### ISSUE THREAD

**Issue by andreyferriyan** [stasinopoulos/commix#41]
![1](https://cloud.githubusercontent.com/assets/5491449/18078040/a5ac23bc-6eb3-11e6-9a9e-6d9bbe043a61.png)
![2](https://cloud.githubusercontent.com/assets/5491449/18078042/a9a34658-6eb3-11e6-9027-9d08983002b4.png)

I try the example from https://www.youtube.com/watch?v=A57pbJA706U and the reverse_tcp is not working. Next I try to connect the reverse_tcp from metasploit using telnet from shell it can connect just for a while. 

But it strange when I try to take out the PHP reverse_tcp code from ./commix/src/core/shells/reverse_tcp.py into their own file let say rev_tcp.php then I try again the reverse_tcp is working.

![4](https://cloud.githubusercontent.com/assets/5491449/18078664/fd3c5036-6eb6-11e6-8411-b280dfedaa74.png)

![3](https://cloud.githubusercontent.com/assets/5491449/18078670/04883ecc-6eb7-11e6-83e2-8a5251edfd88.png)

**Comment by stasinopoulos** [comment]
Sorry but I can't find the reason why it is not working. 
Try to use "-v1" option to see the requested payload and then try manually to execute it over the vulnerable application.

**Comment by gaurang8492** [comment]
@andreyferriyan Did u managed to get meterpreter using reverse_tcp?
Even i am having the same problem. Reverse_tcp isn't working in my case.
I am getting the same error ```[x] Critical: The reverse TCP connection has failed!```
