### ISSUE TITLE
Inject GET parameter in POST request 

### ISSUE THREAD

**Issue by Tompazi** [stasinopoulos/commix#42]
Hi, I like your tool a lot, but I have a problem.

here is a simplified version of what I want to do:

`commix -u http://10.0.0.1/index.pl?INJECT_HERE --data=$POST_DATA`

I want to inject into the URL (yes directly after the '?' there is no parameter name), but commix sees it's a POST request and happily starts to inject POST parameters, completely ignoring the INJECT_HERE tag in the URL. Even with a parameter name and the '-p' option it only looks for the parameter in the post data.
ONLY POST PARAMETERS ARE TESTED.

Is there currently a way how to do this? If not, I really think this should be possible to do with commix without having to write a http proxy that adds the post data afterwards...

Also I miss the possibility to skip parameters/tests during tests or please tell me if this is possible.

using version 1.3.16 as delivered in Kali Linux.

Cheers

**Comment by stasinopoulos** [comment]
Hey @Tompazi, try to use the "\*" wildcard in order to specify where to inject (in the URI) without any other parameters i.e. `commix -u http://10.0.0.1/index.pl?*`

**Comment by Tompazi** [comment]
Same result, keep in mind there is also POST data.

also: 
```
$ grep INJECT_TAG /usr/share/commix/src/utils/settings.py
INJECT_TAG = "INJECT_HERE"
grep VERSION_NUM /usr/share/commix/src/utils/settings.py -m 1
VERSION_NUM = "1.3.16"
```
Am I using the wrong version?

**Comment by stasinopoulos** [comment]
Try to use `commix -u http://10.0.0.1/index.pl?*` and then enter your post data.

**Comment by Tompazi** [comment]
I'm sorry but what do you mean? How shouId I enter my post data, I do it like this:

`commix -u http://10.0.0.1/index.pl?* --data=$POST_DATA`

It's still only injecting the post parameters.

**Comment by stasinopoulos** [comment]
You should be entering it like this: `commix -u http://10.0.0.1/index.pl/* --data="POST_DATA"` (without the $ symbol). For example, if there are two POST A and B parameters and you want to test the URL itself, you should write: `commix -u http://10.0.0.1/index.pl/* --data="A=whatever&B=whatever"`. (The "INJECT_HERE" is replaced by "*".) For more info, please check Commix Wiki Page at https://github.com/stasinopoulos/commix/wiki/Usage-Examples.

**Comment by Tompazi** [comment]
I think we are not communicating correctly. Look at this, is this intended behavior?
![commix1](https://cloud.githubusercontent.com/assets/22277474/18644968/a176012a-7eab-11e6-8e2d-762e6e950b5e.png)
![commix2](https://cloud.githubusercontent.com/assets/22277474/18644967/a1730f92-7eab-11e6-8b12-1c1b6ab07dcc.png)

**Comment by palaziv** [comment]
@stasinopoulos I have the same problem. I try to test the URL parameter "foo" in the following example HTTP POST request:

POST /whatever/bla.asp?**foo**=bar
Host: example.com
Content-Type: application/x-www-form-urlencoded
[...]

val1=1&val2=2&val3=3


Now when I try to run commix like so _python3 commix.py --url "https://example.com/whatever/bla.asp?foo=bar*" --data="val1=1&val2=2&val3=3" -p foo_ commix refuses to test the "foo" parameter with the message "[warning] Skipping tests for the provided parameter 'foo' as it is not part of the POST data."

Is it possible to force commix to test that parameter anyway?
