### ISSUE TITLE
durin work it is 

### ISSUE THREAD

**Issue by hcstorm** [stasinopoulos/commix#9]
Hi why commix canot do injection realy  on website  it is give me command could not return any output, due to pipe (|) filtration on target.
this is mean that it is weak agnis filtration

**Comment by stasinopoulos** [comment]
Hey, @hcstorm according to the warning message that you mention, i can assume that there is a pipe command filtration on target. This is not an error of commix, so this issue will close. Thanks.

**Comment by hcstorm** [comment]
i mean that commix can't do all shell injections
